services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        whatwedo\WorkflowBundle\EventHandler\WorkflowSubscriberAbstract:
            tags: ['workflow.event_handler']
            public: true


    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    whatwedo\WorkflowBundle\:
        resource: '../../*'
        exclude: '../{Entity}'


#    whatwedo\WorkflowBundle\Form\WorkflowEventSubscriberTypes: ~
#
    whatwedo\WorkflowBundle\Manager\WorkflowManager: ~

#    whatwedo\WorkflowBundle\Service\WorkflowService: ~

    whatwedo\WorkflowBundle\Service\WorkflowService:
        arguments: [ whatwedo\WorkflowBundle\Manager\WorkflowManager]
#
#    whatwedo\WorkflowBundle\Controller\:
#        resource: '../../Controller'
#        tags: ['controller.service_arguments']
#
#
#    whatwedo\WorkflowBundle\Controller\ApplyController:
#        calls:
#            - [setWorkflowRegistry, ['whatwedo\WorkflowBundle\Service\WorkflowService']]
#

    'workflow.registry':
        class: whatwedo\WorkflowBundle\Service\WorkflowService
